version: '3'
services:
    ddagent:
      image: datadog/agent:latest
      container_name: datadog-agent-p
      env_file:
        - ~/sandbox.docker.env
      environment:
        - DD_APM_ENABLED=true
        - DD_LOGS_ENABLED=true
        - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
        - DD_APM_NON_LOCAL_TRAFFIC=true
        # - DD_AC_EXCLUDE=name:datadog-agent-ft
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      ports:
        - "8126:8126"
      restart: on-failure
    flask_server:
    #   image: cahillsf/ps-flask:test
      build:
        dockerfile: Dockerfile
        context: ./flask-server
      environment: 
        - DD_AGENT_HOST=datadog-agent-p
        # - DD_TRACE_DEBUG=true
      ports:
        - '8000:8000'
    # vue_web:
    #   image: cahillsf/ps-vue:test
    #   # build:
    #   #   dockerfile: Dockerfile
    #     # dockerfile: Dockerfiledev
    #     # context: ./funvue
    #   env_file:
    #     - ~/sandbox.docker.env
    #   ports:
    #     - '8080:8080'